### ISSUE TITLE
PCBway

### ISSUE THREAD

**Issue by civarson** [Cipulot/RF_R1_8-9Xu#1]
Hi, thank you for providing this. I just submitted an order to print one of these based on the files you've provided (gerber files and BOM) and included assembly in the order. Note that for the BOM item "220 @ 100MHz, 2A", the part number you reference is 330 ohms and not 220 (C85832).

Is there anything else I need to know since this is my first time doing it? I am doing this as I've always wanted to get a custom PCB printed, plus I have been eager to convert my R1 to usb-c for several years now.

My minimum order is 5 assembled boards if anyone wants to DM me to purchase (cost + shipping). I'll have 4 leftover!

**Comment by Cipulot** [comment]
@civarson that will be fixed.

If you want to purchase a unit, they are currently available for purchase at Cannonkeys. 

As a final note, please, do not utilize the GH issues as a marketplace for the leftovers MOQ.....
